const HomeLanding = () => {
    return (
        <div id="home" className="bg-gradient-to-tr from-red-600 to-orange-500 text-white">
            <h1>Ini Halaman home</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur accusantium dolore nulla quasi pariatur hic repellat quod. Ratione odit odio nostrum quia. Quasi praesentium dolorum nobis, ipsa cupiditate ea impedit totam alias placeat sequi maiores repellat ipsam aliquid quo dolorem! Nesciunt delectus tempora corporis sunt soluta a deleniti neque quaerat quisquam? Est itaque commodi repellat asperiores ex aliquam, deserunt iusto laborum eius! Ducimus eius vel repudiandae accusantium veritatis, nobis hic suscipit architecto eligendi reiciendis! Suscipit eum hic, consequuntur quidem non animi voluptas nesciunt libero corporis dolores repellat, officiis ducimus obcaecati dignissimos cupiditate aut distinctio cum maxime eos, incidunt nemo ea.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur accusantium dolore nulla quasi pariatur hic repellat quod. Ratione odit odio nostrum quia. Quasi praesentium dolorum nobis, ipsa cupiditate ea impedit totam alias placeat sequi maiores repellat ipsam aliquid quo dolorem! Nesciunt delectus tempora corporis sunt soluta a deleniti neque quaerat quisquam? Est itaque commodi repellat asperiores ex aliquam, deserunt iusto laborum eius! Ducimus eius vel repudiandae accusantium veritatis, nobis hic suscipit architecto eligendi reiciendis! Suscipit eum hic, consequuntur quidem non animi voluptas nesciunt libero corporis dolores repellat, officiis ducimus obcaecati dignissimos cupiditate aut distinctio cum maxime eos, incidunt nemo ea.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur accusantium dolore nulla quasi pariatur hic repellat quod. Ratione odit odio nostrum quia. Quasi praesentium dolorum nobis, ipsa cupiditate ea impedit totam alias placeat sequi maiores repellat ipsam aliquid quo dolorem! Nesciunt delectus tempora corporis sunt soluta a deleniti neque quaerat quisquam? Est itaque commodi repellat asperiores ex aliquam, deserunt iusto laborum eius! Ducimus eius vel repudiandae accusantium veritatis, nobis hic suscipit architecto eligendi reiciendis! Suscipit eum hic, consequuntur quidem non animi voluptas nesciunt libero corporis dolores repellat, officiis ducimus obcaecati dignissimos cupiditate aut distinctio cum maxime eos, incidunt nemo ea.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur accusantium dolore nulla quasi pariatur hic repellat quod. Ratione odit odio nostrum quia. Quasi praesentium dolorum nobis, ipsa cupiditate ea impedit totam alias placeat sequi maiores repellat ipsam aliquid quo dolorem! Nesciunt delectus tempora corporis sunt soluta a deleniti neque quaerat quisquam? Est itaque commodi repellat asperiores ex aliquam, deserunt iusto laborum eius! Ducimus eius vel repudiandae accusantium veritatis, nobis hic suscipit architecto eligendi reiciendis! Suscipit eum hic, consequuntur quidem non animi voluptas nesciunt libero corporis dolores repellat, officiis ducimus obcaecati dignissimos cupiditate aut distinctio cum maxime eos, incidunt nemo ea.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur accusantium dolore nulla quasi pariatur hic repellat quod. Ratione odit odio nostrum quia. Quasi praesentium dolorum nobis, ipsa cupiditate ea impedit totam alias placeat sequi maiores repellat ipsam aliquid quo dolorem! Nesciunt delectus tempora corporis sunt soluta a deleniti neque quaerat quisquam? Est itaque commodi repellat asperiores ex aliquam, deserunt iusto laborum eius! Ducimus eius vel repudiandae accusantium veritatis, nobis hic suscipit architecto eligendi reiciendis! Suscipit eum hic, consequuntur quidem non animi voluptas nesciunt libero corporis dolores repellat, officiis ducimus obcaecati dignissimos cupiditate aut distinctio cum maxime eos, incidunt nemo ea.</p>
        </div>
    )
}
export default HomeLanding;